services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      php-fpm:
        condition: service_healthy
    networks:
      - slim-network

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php-fpm/log:/var/log/php
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/conf.d:/usr/local/etc/php/conf.d
    healthcheck:
      test: [ "CMD-SHELL", "php-fpm -t || exit 1" ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - slim-network

  mysql:
    build:
      context: ./docker/mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - slim-network

networks:
  slim-network:
    driver: bridge